// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Sourcegraph.Cody
{
    internal sealed partial class Vsix
    {
        public const string Id = "Sourcegraph.Cody";
        public const string Name = "Sourcegraph Cody";
        public const string Description = @"AI coding assistant that uses search and codebase context to help you write code faster. Cody brings autocomplete, chat, and commands to VS, so you can generate code, write unit tests, create docs, and explain complex code using AI.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Sourcegraph Tests";
        public const string Tags = "";
    }
}
