name: Publish

on:
  push:
    tags:
      - v*

jobs:
  release:
    if: github.repository == 'sourcegraph/cody-vs'
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3

      - name: Install Cake.Tool
        run: dotnet tool install --global Cake.Tool

      - name: Restore NuGet packages
        run: nuget restore src\Cody.Core\Cody.Core.csproj -PackagesDirectory src\packages

      - name: Run Cake script
        env:
          CODY_VS_MARKETPLACE_RELEASE_TOKEN: ${{ secrets.CODY_VS_MARKETPLACE_RELEASE_TOKEN }}
        run: |
          cd src
          dotnet tool restore
          corepack enable
          corepack install --global pnpm@8.6.7
       
      - name: Publish to marketplace
        env:
          CODY_VS_MARKETPLACE_RELEASE_TOKEN: ${{ secrets.CODY_VS_MARKETPLACE_RELEASE_TOKEN }}
        run: dotnet cake --target Publish
